apiVersion: v1
kind: ConfigMap
metadata:
  name: web-mgmt
data:
  web-mgmt.cfg: |
    top; configure terminal;
    web-mgmt
      admin-state enabled
      local-address 0.0.0.0
      port 9090
      save-config-overwrite
      idle-timeout 9000
      ssl-config-type server
    exit